name: Autocorrección (standalone)

on:
  repository_dispatch:
    types: [autocorreccion]
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  evaluar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alumno (main)
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 1

      - name: Checkout rubricas
        uses: actions/checkout@v4
        with:
          repository: 4GAES/rubricas
          path: rubricas
          ref: main
          fetch-depth: 1

      - name: Configurar entorno Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias requeridas
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests python-dotenv rich

      - name: Run evaluator (GPT-5 nano)
        env:
          KLAUS: ${{ secrets.KLAUS }}
          USE_LLM_RUBRIC: "1" 
          # payload: pasa la cadena desde tu backend o edítalo aquí:
          CLIENT_PAYLOAD_JSON: >-
            {
              "slug": "instagram-feed-bootstrap",
              "rubrics_ref": "main",
              "rubrics_chain": [
                "modules/intro_web@1.0.0.yaml",
                "stacks/frontend-js@1.0.0.yaml",
                "globals/base@1.yaml"
              ],
              "scoring": {
                "type":"A",
                "ensemble_size":1,
                "max_context_bytes":250000,
                "model":"gpt-5-nano"
              },
              "problem_path": "",
              "solution_path": ""
            }
        run: |
          python .github/tools/auto_evaluator.py

      - name: Ensure labels exist
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          ensure_label() {
            local name="$1"; local color="${2:-C5DEF5}"; local desc="${3:-Auto label}"
            if ! gh label list --limit 200 --json name --jq '.[].name' | grep -Fxq "$name"; then
              gh label create "$name" --color "$color" --description "$desc" || true
            fi
          }
          # Creamos solo labels estables (evita spam de miles de etiquetas)
          ensure_label "autocorreccion" "FBCA04" "Corrección automática"
          ensure_label "slug:instagram-feed-bootstrap" "0E8A16" "Proyecto"
          ensure_label "branch:main" "1D76DB" "Rama"

      - name: Crear/actualizar Issue (por SHA en el título)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          SHA_SHORT=$(git rev-parse --short HEAD)
          TITLE="[AutoCorrección] instagram-feed-bootstrap - main@${SHA_SHORT}"
          LABELS="autocorreccion,slug:instagram-feed-bootstrap,branch:main"
      
          # ¿ya existe este exacto?
          existing=$(gh issue list --limit 100 --search "$TITLE in:title" --json number --jq '.[0].number' || true)
      
          if [ -n "${existing:-}" ]; then
            gh issue edit "$existing" --add-label "$LABELS" --body-file ISSUE_BODY.md
          else
            # cerramos issues previos abiertos del mismo slug/branch
            old=$(gh issue list --limit 100 --search "[AutoCorrección] instagram-feed-bootstrap - main@ in:title state:open" --json number,title --jq '.[] | select(.title != "'"$TITLE"'") | .number' || true)
            for n in $old; do
              gh issue close "$n" --comment "Nueva entrega detectada (main@${SHA_SHORT})."
            done
            gh issue create --title "$TITLE" --label "$LABELS" --body-file ISSUE_BODY.md
          fi

      - name: Subir artefactos
        uses: actions/upload-artifact@v4
        with:
          name: reporte
          path: |
            results.csv
            evaluation.log
            scanner_meta.json
            rubrica_efectiva.yaml
            ISSUE_BODY.md
